######################
# book (meta) info

title: مبادئ وتقنيات علم البيانات
author: 
  name: Ali Alohali

github:
  url: "https://github.com/bookdesigns/book-epsilon"

########
# more settings

url:              ''
baseurl:          ''
rss:              RSS

collections:
  chapters:
      output: false

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md

