######################
# book (meta) info

title: مبادئ وتقنيات علم البيانات
author: 
  name: Ali Alohali

########
# more settings

url:              ''
baseurl:          '/ds-100-ar'
rss:              RSS

collections:
  chapters:
      output: false

# sass:
#   sass_dir: css
#   style:    expanded

google_analytics: UA-134016492-1
google_ad_client: ca-pub-8513572715092457

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
- _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji